name: Update Wiki

on:
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check out wiki repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          path: .wiki

      - name: Copy README.md to wiki
        run: cp README.md .wiki/Home.md

      - name: Push changes
        run: |
          cd .wiki
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update wiki from README.md" || exit 0  # Don't fail if no changes
          git push